- name: Build CMake
  uses: ashutoshvarma/action-cmake-build@v1
  with:
    # Build directory where build files will be generated
    # C Compiler for toolchain
    cc: clang # optional
    # C++ Compiler for toolchain
    cxx: clang++ # optional
    # Update git submodules
    submodule-update: true # optional, default is false
